### PR TITLE
Pull Request for Mint Sign Up form

### PR DESCRIPTION
**Pull request by teekaytech**
## Finished working on:

-  Structuring the sign-up page
-  Added contents to the header, main and footer sections of the page
-  Styled the SignUp page to look like the origin mint signup page
-  Added .stickler.yml and stylelint.config.js as a linter
-  Validated index.html with W3C Validator

### CODE REVIEW

**Comment by uryelah** [comment]
### Pull Request under the review by Sarah Uryelah Silva Chamorro (TSE)

**Comment by uryelah** [comment]
Hello **Phillip Musiime** & **Taofeek Olalere**, I'm Sarah, your reviewer for this PR . 👷 

**Your project is not yet approved but, you did an amazing job cloning the intuit page, the styling looks really well done 👏👏👏**

**Congrats for:**
- making a perfect sign-in and sign-up buttons
- paying attention to the border color and icons
- utilizing the form and input forms well
- utilizing the `required` field on the required inputs
- making descriptive commit messages
- writing a descriptive PR title and description
- making a great README.md file with the image included

----

### REQUIRED CHANGES

- [ ] Make sure that your project passes all the Stickler checks. Please fix the lint errors found.
Screenshot_2020-02-24 Pull Request for Mint Sign Up form by teekaytech · Pull Request #1 · PhillipUg mint-clone

- [ ] [Id selectors are not the best practice](https://webdesigntips.blog/web-design/css-tricks/dont-use-ids-in-css-selectors/) when styling CSS, please change them to class selectors.

- [ ] Make sure that the text at the header area has the same color as the [one in the original site](https://accounts.intuit.com/signup.html).
Screenshot_2020-02-24 Intuit Accounts - Sign Up

---

## OPTIONAL CHANGES

- [ ] [OPTIONAL] For a more semantic Markup use the `<nav>` tag instead of a `div` for the element with the id `header-div`

-------

### Kindly fix the required changes and then request another code review.

Cheers and Happy coding! 🎉 

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by uryelah** [comment]
Hey **Phillip Musiime** & **Taofeek Olalere** 👋  

**You did a really good job fixing the id selectors and logo area 😸,  but you still have linting errors**:

Screenshot_2020-02-24 Pull Request for Mint Sign Up form by teekaytech · Pull Request #1 · PhillipUg mint-clone(1)

----

### REQUIRED CHANGES

- [ ] Fix All remaining Stickler checks

----

### Kindly fix the required changes and then request another code review.

Cheers and Happy coding! 🎉 

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by PhillipUg** [comment]
## Fixes

- Fixed all linter errors
- Header text color fixed as well
- All ids used for css styling have been changed to classes

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

- [ ] It’s better to delete commented code on your CSS file.  [Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) you can see the information about this.
COMMENTLINE

[OPTIONAL]

- [ ] Consider adding the 'demo' link in your readme file.

- [ ] I encourage you to use the `<nav>` tag for the major navigation links.

- [ ] I encourage you to use the `<main>` tag for the dominant content of the `<body>` of a document.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by teekaytech** [comment]
## In this fix, we improved on the following:
- Commented codes are deleted in CSS (style.css) file
- The pull request description is short and concise.
- The demo link is added to the README file.
- <nav> tag has been used for navigation link
- <main> tag was also used for the dominant content.

**Review by nikasulo — APPROVED** [review]
# Hey team @PhillipUg and @teekaytech :wave: 
Great work implementing the changes suggested by @SofiBretz, you have put in the work and I congratulate you 👌. That being said, you may merge and move one. I wish you the very best, see you at the top 😊

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
